name: ci-build-asp.net-project

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'

      - name: List files
        run: ls -R

      - name: Restore deps
        run: dotnet restore 

      - name: Build
        run: dotnet build  --configuration Release --no-restore